/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davi.sischool.forms;

import br.com.davi.sischool.model.Funcionario;
import br.com.davi.sischool.model.Login;
import br.com.davi.sischool.funcoes.AbrirTelas;
import br.com.davi.sischool.model.OutroCargo;
import br.com.davi.sischool.model.Transferencia;
import br.com.davi.sischool.regras.OutroCargoDAO;
import br.com.davi.sischool.regras.TransferenciaDAO;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.event.WindowStateListener;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Davi
 */
public final class JFPrincipal extends javax.swing.JFrame {
    
    private JFPrincipal() {    
    }
    
    /**
     * Cria um novo JFPrincipal
     * @param login
     */
    public JFPrincipal(Login login) {
        this.login = login;
        func = login.getFunc();
        initComponents();
        iniciaComponentes();
        preencheLogin();
    }
    
    private void iniciaComponentes(){
        setaListeners();
    }
    
    private void setaListeners(){
        btnMinimizar.addActionListener(oa);
        btnMaximizar.addActionListener(oa);
        btnFechar.addActionListener(oa);
        btnEstatisticas.addActionListener(oa);
        btnConsultar.addActionListener(oa);
        btnCronogramaDeAulas.addActionListener(oa);
        btnCadastrarEscola.addActionListener(oa);
        btnCadFunc.addActionListener(oa);
        //btnInfo.addActionListener(oa);
        btnWarning.addActionListener(oa);
        //btnDevCad.addActionListener(oa);
        btnHelp.addActionListener(oa);
        btnCadastrarAluno.addActionListener(oa);
        btnNotasProf.addActionListener(oa);
        btnTransferirAluno.addActionListener(oa);
        btnAtribuirProf.addActionListener(oa);
        btnProfTurmasII.addActionListener(oa);
        btnSeguranca.addActionListener(oa);
        btnLogout.addActionListener(oa);
        btnCriarTurmas.addActionListener(oa);
        btnHelp.addActionListener(oa);
        
        this.addWindowListener(new OuvintesWindowsListener());
    }
    
    private void checaTransferencias(){
        if (func.getAcesso()>=1){
            boolean temTrans = false;
            OutroCargo oc = new OutroCargo();
            OutroCargoDAO ocdao = new OutroCargoDAO();

            oc = ocdao.buscarFunc(func.getId());

            TransferenciaDAO tdao = new TransferenciaDAO();
            for (Transferencia t: tdao.buscaTodas()){
                if (t.getAluno().getEscola().getId() == oc.getEscola().getId()){
                    temTrans = true;
                }
            }

            if (temTrans){
                btnWarning.setEnabled(true);
            } else {
                btnWarning.setEnabled(false);
            }
        }
    }
    
    private void abrirPdf(){
        Desktop desktop = Desktop.getDesktop();  
        try {
            desktop.open(new File("C:\\Users\\Davi\\Downloads\\Eduvale\\TCC\\SiSchool\\Manual-Do-Usuario.pdf"));
        } catch (IOException ex) {
            System.out.println("Arquivo não encontrado.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelBarraDeTitulo = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        lblTituloPrincipal = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        tabbedPaneUsuarios = new javax.swing.JTabbedPane();
        paneTabGeral = new javax.swing.JPanel();
        paneIconesTelaGeral = new javax.swing.JPanel();
        panelBtnConsultar = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelBtnCronogramaDeAulas = new javax.swing.JPanel();
        btnCronogramaDeAulas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelBtnCadastrarEscola = new javax.swing.JPanel();
        btnCadastrarEscola = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        paneBtnCadFunc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCadFunc = new javax.swing.JButton();
        paneIconesTelaGeral2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCriarTurmas = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelBtnEstatisticas = new javax.swing.JPanel();
        btnEstatisticas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        paneTabAlunos = new javax.swing.JPanel();
        paneIconesTelaAlunos = new javax.swing.JPanel();
        panelBtnEstatisticasProf = new javax.swing.JPanel();
        btnTransferirAluno = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelBtnNotasProf = new javax.swing.JPanel();
        btnNotasProf = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelBtnCadastrarAluno = new javax.swing.JPanel();
        btnCadastrarAluno = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        paneTabProfessores = new javax.swing.JPanel();
        paneIconesTelaProfessores = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnAtribuirProf = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnProfTurmasII = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        paneTabSeguranca = new javax.swing.JPanel();
        panePartedeCima = new javax.swing.JPanel();
        panelBackup = new javax.swing.JPanel();
        btnSeguranca = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        panelMenuLateral = new javax.swing.JPanel();
        btnWarning = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setExtendedState(NORMAL);
        setLocation(new java.awt.Point(0, 0));
        setName("framePrincipal"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPrincipal.setName("panelPrincipal"); // NOI18N

        panelBarraDeTitulo.setBackground(new java.awt.Color(0, 0, 102));
        panelBarraDeTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/red.png"))); // NOI18N
        btnFechar.setContentAreaFilled(false);
        btnFechar.setName("btnFechar"); // NOI18N

        lblTituloPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPrincipal.setText("SiSchool - Tela Principal");

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/yellow.png"))); // NOI18N
        btnMaximizar.setContentAreaFilled(false);
        btnMaximizar.setName("btnMaximizar"); // NOI18N

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/green.png"))); // NOI18N
        btnMinimizar.setContentAreaFilled(false);

        javax.swing.GroupLayout panelBarraDeTituloLayout = new javax.swing.GroupLayout(panelBarraDeTitulo);
        panelBarraDeTitulo.setLayout(panelBarraDeTituloLayout);
        panelBarraDeTituloLayout.setHorizontalGroup(
            panelBarraDeTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDeTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelBarraDeTituloLayout.setVerticalGroup(
            panelBarraDeTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDeTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBarraDeTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPrincipal)
                    .addGroup(panelBarraDeTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnMinimizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnMaximizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(407, 407, 407))
        );

        tabbedPaneUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        tabbedPaneUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabbedPaneUsuarios.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedPaneUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabbedPaneUsuarios.setName("tabbedPaneUsuarios"); // NOI18N

        paneTabGeral.setBackground(new java.awt.Color(204, 204, 204));
        paneTabGeral.setName("tabEscriturarios"); // NOI18N
        paneTabGeral.setLayout(new java.awt.GridLayout(2, 1));

        paneIconesTelaGeral.setBackground(new java.awt.Color(204, 204, 204));

        panelBtnConsultar.setBackground(new java.awt.Color(204, 204, 204));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/consulta.png"))); // NOI18N
        btnConsultar.setContentAreaFilled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setLabelFor(btnConsultar);
        jLabel2.setText("Consultar");

        javax.swing.GroupLayout panelBtnConsultarLayout = new javax.swing.GroupLayout(panelBtnConsultar);
        panelBtnConsultar.setLayout(panelBtnConsultarLayout);
        panelBtnConsultarLayout.setHorizontalGroup(
            panelBtnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBtnConsultarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnConsultarLayout.setVerticalGroup(
            panelBtnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnConsultarLayout.createSequentialGroup()
                .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        panelBtnCronogramaDeAulas.setBackground(new java.awt.Color(204, 204, 204));

        btnCronogramaDeAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/cronogramaDeAulas.png"))); // NOI18N
        btnCronogramaDeAulas.setContentAreaFilled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setLabelFor(btnCronogramaDeAulas);
        jLabel3.setText("Cronograma de Aulas");

        javax.swing.GroupLayout panelBtnCronogramaDeAulasLayout = new javax.swing.GroupLayout(panelBtnCronogramaDeAulas);
        panelBtnCronogramaDeAulas.setLayout(panelBtnCronogramaDeAulasLayout);
        panelBtnCronogramaDeAulasLayout.setHorizontalGroup(
            panelBtnCronogramaDeAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCronogramaDeAulas, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnCronogramaDeAulasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        panelBtnCronogramaDeAulasLayout.setVerticalGroup(
            panelBtnCronogramaDeAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnCronogramaDeAulasLayout.createSequentialGroup()
                .addComponent(btnCronogramaDeAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBtnCadastrarEscola.setBackground(new java.awt.Color(204, 204, 204));

        btnCadastrarEscola.setBackground(new java.awt.Color(204, 204, 204));
        btnCadastrarEscola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/cadastrarEscola.png"))); // NOI18N
        btnCadastrarEscola.setContentAreaFilled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setLabelFor(btnCadastrarEscola);
        jLabel4.setText("Cadastrar Escola");

        javax.swing.GroupLayout panelBtnCadastrarEscolaLayout = new javax.swing.GroupLayout(panelBtnCadastrarEscola);
        panelBtnCadastrarEscola.setLayout(panelBtnCadastrarEscolaLayout);
        panelBtnCadastrarEscolaLayout.setHorizontalGroup(
            panelBtnCadastrarEscolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadastrarEscola, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(panelBtnCadastrarEscolaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnCadastrarEscolaLayout.setVerticalGroup(
            panelBtnCadastrarEscolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnCadastrarEscolaLayout.createSequentialGroup()
                .addComponent(btnCadastrarEscola, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        paneBtnCadFunc.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setLabelFor(btnCadFunc);
        jLabel7.setText(" Cadastrar Funcionário");

        btnCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/cadastroFunc.png"))); // NOI18N
        btnCadFunc.setContentAreaFilled(false);

        javax.swing.GroupLayout paneBtnCadFuncLayout = new javax.swing.GroupLayout(paneBtnCadFunc);
        paneBtnCadFunc.setLayout(paneBtnCadFuncLayout);
        paneBtnCadFuncLayout.setHorizontalGroup(
            paneBtnCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBtnCadFuncLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(paneBtnCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBtnCadFuncLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBtnCadFuncLayout.createSequentialGroup()
                        .addComponent(btnCadFunc)
                        .addGap(20, 20, 20))))
        );
        paneBtnCadFuncLayout.setVerticalGroup(
            paneBtnCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBtnCadFuncLayout.createSequentialGroup()
                .addComponent(btnCadFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );

        javax.swing.GroupLayout paneIconesTelaGeralLayout = new javax.swing.GroupLayout(paneIconesTelaGeral);
        paneIconesTelaGeral.setLayout(paneIconesTelaGeralLayout);
        paneIconesTelaGeralLayout.setHorizontalGroup(
            paneIconesTelaGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaGeralLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(panelBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(paneBtnCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(panelBtnCronogramaDeAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(panelBtnCadastrarEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        paneIconesTelaGeralLayout.setVerticalGroup(
            paneIconesTelaGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaGeralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paneIconesTelaGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBtnCadastrarEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBtnCronogramaDeAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBtnCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        paneTabGeral.add(paneIconesTelaGeral);

        paneIconesTelaGeral2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        btnCriarTurmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/turma.png"))); // NOI18N
        btnCriarTurmas.setContentAreaFilled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Gestão de Turmas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCriarTurmas))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnCriarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBtnEstatisticas.setBackground(new java.awt.Color(204, 204, 204));

        btnEstatisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/estatisticas.png"))); // NOI18N
        btnEstatisticas.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setLabelFor(btnTransferirAluno);
        jLabel1.setText("Estatísticas");

        javax.swing.GroupLayout panelBtnEstatisticasLayout = new javax.swing.GroupLayout(panelBtnEstatisticas);
        panelBtnEstatisticas.setLayout(panelBtnEstatisticasLayout);
        panelBtnEstatisticasLayout.setHorizontalGroup(
            panelBtnEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnEstatisticasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );
        panelBtnEstatisticasLayout.setVerticalGroup(
            panelBtnEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnEstatisticasLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(btnEstatisticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout paneIconesTelaGeral2Layout = new javax.swing.GroupLayout(paneIconesTelaGeral2);
        paneIconesTelaGeral2.setLayout(paneIconesTelaGeral2Layout);
        paneIconesTelaGeral2Layout.setHorizontalGroup(
            paneIconesTelaGeral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaGeral2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(panelBtnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        paneIconesTelaGeral2Layout.setVerticalGroup(
            paneIconesTelaGeral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaGeral2Layout.createSequentialGroup()
                .addGroup(paneIconesTelaGeral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIconesTelaGeral2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(paneIconesTelaGeral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelBtnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneIconesTelaGeral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(paneIconesTelaGeral2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        paneTabGeral.add(paneIconesTelaGeral2);

        tabbedPaneUsuarios.addTab("Geral", paneTabGeral);

        paneTabAlunos.setBackground(new java.awt.Color(204, 204, 204));
        paneTabAlunos.setName("tabProfessores"); // NOI18N
        paneTabAlunos.setLayout(new java.awt.GridLayout(2, 1));

        paneIconesTelaAlunos.setBackground(new java.awt.Color(204, 204, 204));

        panelBtnEstatisticasProf.setBackground(new java.awt.Color(204, 204, 204));

        btnTransferirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/transferirAlunos.png"))); // NOI18N
        btnTransferirAluno.setContentAreaFilled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Transferir Aluno");

        javax.swing.GroupLayout panelBtnEstatisticasProfLayout = new javax.swing.GroupLayout(panelBtnEstatisticasProf);
        panelBtnEstatisticasProf.setLayout(panelBtnEstatisticasProfLayout);
        panelBtnEstatisticasProfLayout.setHorizontalGroup(
            panelBtnEstatisticasProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnEstatisticasProfLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(panelBtnEstatisticasProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBtnEstatisticasProfLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(btnTransferirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelBtnEstatisticasProfLayout.setVerticalGroup(
            panelBtnEstatisticasProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnEstatisticasProfLayout.createSequentialGroup()
                .addComponent(btnTransferirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        panelBtnNotasProf.setBackground(new java.awt.Color(204, 204, 204));

        btnNotasProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/notas.png"))); // NOI18N
        btnNotasProf.setContentAreaFilled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Notas e Faltas");

        javax.swing.GroupLayout panelBtnNotasProfLayout = new javax.swing.GroupLayout(panelBtnNotasProf);
        panelBtnNotasProf.setLayout(panelBtnNotasProfLayout);
        panelBtnNotasProfLayout.setHorizontalGroup(
            panelBtnNotasProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNotasProf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
            .addGroup(panelBtnNotasProfLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnNotasProfLayout.setVerticalGroup(
            panelBtnNotasProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnNotasProfLayout.createSequentialGroup()
                .addComponent(btnNotasProf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBtnCadastrarAluno.setBackground(new java.awt.Color(204, 204, 204));

        btnCadastrarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/cadastrarAlunos.png"))); // NOI18N
        btnCadastrarAluno.setContentAreaFilled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Cadastrar Aluno");

        javax.swing.GroupLayout panelBtnCadastrarAlunoLayout = new javax.swing.GroupLayout(panelBtnCadastrarAluno);
        panelBtnCadastrarAluno.setLayout(panelBtnCadastrarAlunoLayout);
        panelBtnCadastrarAlunoLayout.setHorizontalGroup(
            panelBtnCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadastrarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnCadastrarAlunoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(20, 20, 20))
        );
        panelBtnCadastrarAlunoLayout.setVerticalGroup(
            panelBtnCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnCadastrarAlunoLayout.createSequentialGroup()
                .addComponent(btnCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneIconesTelaAlunosLayout = new javax.swing.GroupLayout(paneIconesTelaAlunos);
        paneIconesTelaAlunos.setLayout(paneIconesTelaAlunosLayout);
        paneIconesTelaAlunosLayout.setHorizontalGroup(
            paneIconesTelaAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaAlunosLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(panelBtnCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addComponent(panelBtnEstatisticasProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(panelBtnNotasProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        paneIconesTelaAlunosLayout.setVerticalGroup(
            paneIconesTelaAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaAlunosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paneIconesTelaAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBtnNotasProf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelBtnEstatisticasProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBtnCadastrarAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneTabAlunos.add(paneIconesTelaAlunos);

        tabbedPaneUsuarios.addTab("Alunos", paneTabAlunos);
        paneTabAlunos.getAccessibleContext().setAccessibleName("tabProfessores");

        paneTabProfessores.setBackground(new java.awt.Color(204, 204, 204));
        paneTabProfessores.setName("tabSecretaria"); // NOI18N
        paneTabProfessores.setLayout(new java.awt.GridLayout(2, 1));

        paneIconesTelaProfessores.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Atribuição de Turmas");

        btnAtribuirProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/cadastrarProf.png"))); // NOI18N
        btnAtribuirProf.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtribuirProf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAtribuirProf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnProfTurmasII.setBackground(new java.awt.Color(204, 204, 204));
        btnProfTurmasII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/certificado.png"))); // NOI18N
        btnProfTurmasII.setContentAreaFilled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Cadastro de certificados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnProfTurmasII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnProfTurmasII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout paneIconesTelaProfessoresLayout = new javax.swing.GroupLayout(paneIconesTelaProfessores);
        paneIconesTelaProfessores.setLayout(paneIconesTelaProfessoresLayout);
        paneIconesTelaProfessoresLayout.setHorizontalGroup(
            paneIconesTelaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaProfessoresLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        paneIconesTelaProfessoresLayout.setVerticalGroup(
            paneIconesTelaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIconesTelaProfessoresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paneIconesTelaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        paneTabProfessores.add(paneIconesTelaProfessores);

        tabbedPaneUsuarios.addTab("Professores", paneTabProfessores);
        paneTabProfessores.getAccessibleContext().setAccessibleName("tabSecretaria");

        paneTabSeguranca.setBackground(new java.awt.Color(204, 204, 204));
        paneTabSeguranca.setName("tabEja"); // NOI18N

        panePartedeCima.setBackground(new java.awt.Color(204, 204, 204));

        panelBackup.setBackground(new java.awt.Color(204, 204, 204));

        btnSeguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/Backup.png"))); // NOI18N
        btnSeguranca.setContentAreaFilled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Fazer Backup ou Restaurar Dados");

        javax.swing.GroupLayout panelBackupLayout = new javax.swing.GroupLayout(panelBackup);
        panelBackup.setLayout(panelBackupLayout);
        panelBackupLayout.setHorizontalGroup(
            panelBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackupLayout.createSequentialGroup()
                .addGroup(panelBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(panelBackupLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBackupLayout.setVerticalGroup(
            panelBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackupLayout.createSequentialGroup()
                .addComponent(btnSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panePartedeCimaLayout = new javax.swing.GroupLayout(panePartedeCima);
        panePartedeCima.setLayout(panePartedeCimaLayout);
        panePartedeCimaLayout.setHorizontalGroup(
            panePartedeCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePartedeCimaLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(panelBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        panePartedeCimaLayout.setVerticalGroup(
            panePartedeCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePartedeCimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneTabSegurancaLayout = new javax.swing.GroupLayout(paneTabSeguranca);
        paneTabSeguranca.setLayout(paneTabSegurancaLayout);
        paneTabSegurancaLayout.setHorizontalGroup(
            paneTabSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panePartedeCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneTabSegurancaLayout.setVerticalGroup(
            paneTabSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTabSegurancaLayout.createSequentialGroup()
                .addComponent(panePartedeCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 248, Short.MAX_VALUE))
        );

        tabbedPaneUsuarios.addTab("Segurança", paneTabSeguranca);
        paneTabSeguranca.getAccessibleContext().setAccessibleName("tabEja");

        panelMenuLateral.setBackground(new java.awt.Color(204, 204, 204));
        panelMenuLateral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnWarning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/warning.png"))); // NOI18N
        btnWarning.setContentAreaFilled(false);
        btnWarning.setEnabled(false);

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/help.png"))); // NOI18N
        btnHelp.setContentAreaFilled(false);

        javax.swing.GroupLayout panelMenuLateralLayout = new javax.swing.GroupLayout(panelMenuLateral);
        panelMenuLateral.setLayout(panelMenuLateralLayout);
        panelMenuLateralLayout.setHorizontalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelMenuLateralLayout.setVerticalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Usuário:");

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUser.setText("Inserir Nome Aqui");

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davi/sischool/icons/logout.png"))); // NOI18N
        btnLogout.setToolTipText("Sair");
        btnLogout.setContentAreaFilled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Sair");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraDeTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabbedPaneUsuarios))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelBarraDeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(tabbedPaneUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblUser)
                            .addComponent(jLabel14)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );

        tabbedPaneUsuarios.getAccessibleContext().setAccessibleName("tabbedPaneUsuarios");

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
            
    private void preencheLogin(){
        lblUser.setText(func.getNome());
    }
    
    private void maximizar(){
        if (getExtendedState() == MAXIMIZED_BOTH){
            setExtendedState(NORMAL);
        } else {
            setExtendedState(MAXIMIZED_BOTH);
        }
    }
    
    private void logout(){
        login = null;
        this.dispose();
        abrirTelas.abrirJFLogin(login);
    }
    
    private void checaAvisos(){
        if (!func.getCargo().equals("Professor")){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtribuirProf;
    private javax.swing.JButton btnCadFunc;
    private javax.swing.JButton btnCadastrarAluno;
    private javax.swing.JButton btnCadastrarEscola;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCriarTurmas;
    private javax.swing.JButton btnCronogramaDeAulas;
    private javax.swing.JButton btnEstatisticas;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnNotasProf;
    private javax.swing.JButton btnProfTurmasII;
    private javax.swing.JButton btnSeguranca;
    private javax.swing.JButton btnTransferirAluno;
    private javax.swing.JButton btnWarning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel paneBtnCadFunc;
    private javax.swing.JPanel paneIconesTelaAlunos;
    private javax.swing.JPanel paneIconesTelaGeral;
    private javax.swing.JPanel paneIconesTelaGeral2;
    private javax.swing.JPanel paneIconesTelaProfessores;
    private javax.swing.JPanel panePartedeCima;
    private javax.swing.JPanel paneTabAlunos;
    private javax.swing.JPanel paneTabGeral;
    private javax.swing.JPanel paneTabProfessores;
    private javax.swing.JPanel paneTabSeguranca;
    private javax.swing.JPanel panelBackup;
    private javax.swing.JPanel panelBarraDeTitulo;
    private javax.swing.JPanel panelBtnCadastrarAluno;
    private javax.swing.JPanel panelBtnCadastrarEscola;
    private javax.swing.JPanel panelBtnConsultar;
    private javax.swing.JPanel panelBtnCronogramaDeAulas;
    private javax.swing.JPanel panelBtnEstatisticas;
    private javax.swing.JPanel panelBtnEstatisticasProf;
    private javax.swing.JPanel panelBtnNotasProf;
    private javax.swing.JPanel panelMenuLateral;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTabbedPane tabbedPaneUsuarios;
    // End of variables declaration//GEN-END:variables
    public Login login = new Login();
    public Funcionario func = new Funcionario();
    public AbrirTelas abrirTelas = new AbrirTelas();
    public OuvintesAction oa = new OuvintesAction();
    
    private class OuvintesAction implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            if (ae.getSource()==btnSeguranca){
                abrirTelas.abrirJFBackup(login);
            } else if (ae.getSource() == btnFechar){
                System.exit(0);
            } else if (ae.getSource() == btnMinimizar){
                setExtendedState(ICONIFIED);
            } else if (ae.getSource() == btnMaximizar){
                maximizar();
            } else if (ae.getSource() == btnEstatisticas){
                abrirTelas.abrirJFEstatisticas(login);
            } else if (ae.getSource() == btnCadastrarAluno){
                abrirTelas.abrirJFCadastrarAlunos(login);
            } else if (ae.getSource() == btnConsultar){
                abrirTelas.abrirJFConsultas(login);
            } else if (ae.getSource() == btnCadastrarEscola){
                abrirTelas.abrirJFCadastroEscola(login);
            } else if (ae.getSource() == btnCronogramaDeAulas){
                abrirTelas.abrirJFCronograma(login);
            } else if (ae.getSource() == btnNotasProf){
                abrirTelas.abrirJFNotasEFaltas(login);
//            } else if (ae.getSource() == btnDevCad){
//                abrirTelas.abrirJFDevCad(login);
            } else if (ae.getSource() == btnCadFunc){
                abrirTelas.abrirJFCadastrarFuncionarios(login);
            } else if (ae.getSource() == btnLogout){
                logout();
            } else if (ae.getSource() == btnAtribuirProf){
                abrirTelas.abrirJFProfTurmas(login);
            } else if (ae.getSource() == btnEstatisticas){
                abrirTelas.abrirJFTransferirAlunos(login);
            } else if (ae.getSource() == btnWarning){
                abrirTelas.abrirJFAvisos(login);
            } else if (ae.getSource() == btnProfTurmasII){
                abrirTelas.abrirJFProfTurmasPebII(login);
            } else if (ae.getSource() == btnHelp){
                 abrirPdf();
            } else if (ae.getSource() == btnTransferirAluno){
                abrirTelas.abrirJFTransferirAlunos(login);
            } else if (ae.getSource() == btnCriarTurmas){
                abrirTelas.abrirJFCriarTurmas(login);
            }
        }
        
    }
    
    private class OuvintesWindowsListener implements WindowListener {
        @Override
        public void windowOpened(WindowEvent we) {
        }
        @Override
        public void windowClosing(WindowEvent we) {
        }
        @Override
        public void windowClosed(WindowEvent we) {
        }

        @Override
        public void windowIconified(WindowEvent we) {
        }

        @Override
        public void windowDeiconified(WindowEvent we) {
        }
        @Override
        public void windowActivated(WindowEvent we) {
            checaTransferencias();
        }
        @Override
        public void windowDeactivated(WindowEvent we) {
        }

    }
}
